const productDetails = [
    {
        id:1,
        prodid:1,
        stockleft:3,
        price:1.5
    },
   
    {
        id:2,
        prodid:2,
        stockleft:1,
        price:0.90
    },
    {
        id:3,
        prodid:3,
        stockleft:4,
        price:2
    },
    {
        id:4,
        prodid:4,
        stockleft:1,
        price:0.90
    },
    {
        id:5,
        prodid:1,
        stockleft:3,
        price:1.5
    }
]
module.exports=productDetails;